# Generated by Django 3.2.16 on 2024-12-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241203_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='report',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='csv_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='datafile',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='visible_columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportExecution',
        ),
    ]
